### ISSUE TITLE
Incorrect video framerate

### ISSUE THREAD

**Issue by dvschultz** [google/mediapy#3] opened 2021-03-21 07:37 UTC
A video that is 50seconds @ 24fps appears to be 20s @ 60fps in mediapy

<img width="913" alt="Screen Shot 2021-03-21 at 3 35 06 AM" src="https://user-images.githubusercontent.com/161773/111897508-9afa7f00-89f6-11eb-8e1c-32a66df09b56.png">

<img width="1026" alt="Screen Shot 2021-03-21 at 3 34 50 AM" src="https://user-images.githubusercontent.com/161773/111897517-a77ed780-89f6-11eb-8437-583e8c76ae18.png">

**Comment by hhoppe** [comment] 2021-03-21 14:44
Could you please share the input video and the mediapy call(s) so that we can investigate?  Thanks.

**Comment by hhoppe** [comment] 2021-03-22 14:59
Please try including `fps=24` in the `media.show_video()` call.
(The issue is that the `video` retrieved using `read_video()` is a simple `numpy` array without the framerate information.) 

Or, programmatically, one can use:

    with media.VideoReader('https://github.com/hhoppe/data/raw/main/video.mp4') as reader:
      fps = reader.fps
      video = np.array(tuple(reader))
    media.show_video(video, fps=fps)

**Comment by hhoppe** [comment] 2021-04-02 14:33
This should be fixed in https://github.com/google/mediapy/commit/21d54f34fdaea1724be2098c396a8c4fefab308b

Now the framerate should carry through even in the simple case below:

```
import mediapy as media
url = 'https://github.com/hhoppe/data/raw/main/video.mp4'
media.show_video(media.read_video(url))
```

**Closed by hhoppe** 2021-04-02 14:33 UTC
